#!/bin/bash
#
# Signal-to-Site Setup Script
# Run once to configure everything for the demo
#
# Usage: ./setup.sh
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo ""
echo -e "${BLUE}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║          Signal-to-Site Setup                             ║${NC}"
echo -e "${BLUE}║   Hyper-personalized GTM outreach in 60 seconds           ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check for OpenClaw
echo -e "${YELLOW}Checking prerequisites...${NC}"

if ! command -v openclaw &> /dev/null; then
    echo -e "${RED}OpenClaw not found.${NC}"
    echo ""
    echo "Install OpenClaw first:"
    echo "  npm install -g openclaw@latest"
    echo "  openclaw onboard --install-daemon"
    echo ""
    exit 1
fi

echo -e "${GREEN}✓ OpenClaw installed${NC}"

# Check if .env already exists
if [ -f .env ]; then
    echo ""
    echo -e "${YELLOW}Found existing .env file.${NC}"
    read -p "Overwrite? (y/N): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        echo "Keeping existing config. Run 'openclaw plugins install .' to reinstall plugin."
        exit 0
    fi
fi

echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Step 1: Required Configuration${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo ""

# LLM API Key
echo -e "${YELLOW}LLM API Key${NC}"
echo "OpenClaw needs an LLM provider. Anthropic recommended."
echo ""
read -p "ANTHROPIC_API_KEY (or press Enter if already set): " anthropic_key

# Your company info
echo ""
echo -e "${YELLOW}Your Company Info${NC}"
echo "This personalizes the outreach with your details."
echo ""
read -p "Your company name: " company_name
company_name=${company_name:-"Acme Inc"}

read -p "Your value prop (one sentence): " value_prop
value_prop=${value_prop:-"AI automation that saves 10+ hours/week"}

read -p "Your name (for email signature): " sender_name
sender_name=${sender_name:-"Alex"}

read -p "Your title: " sender_title
sender_title=${sender_title:-"Founder"}

read -p "Your email: " sender_email

read -p "Calendly/booking URL: " cta_url
cta_url=${cta_url:-"https://calendly.com/demo"}

echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Step 2: Optional Integrations${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo ""

# Linkt
echo -e "${YELLOW}Linkt Integration (for real GTM signals)${NC}"
echo "Get free credits with code CLAW at https://linkt.ai"
echo ""
read -p "LINKT_API_KEY (or press Enter to skip): " linkt_key

# Netlify
echo ""
echo -e "${YELLOW}Netlify (for live page deployment)${NC}"
echo "Get a token at https://app.netlify.com/user/applications#personal-access-tokens"
echo ""
read -p "NETLIFY_TOKEN (or press Enter for local-only): " netlify_token

# Slack
echo ""
echo -e "${YELLOW}Slack Notifications${NC}"
read -p "SLACK_WEBHOOK_URL (or press Enter to skip): " slack_webhook

echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Creating .env file...${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo ""

# Write .env file
cat > .env << EOF
# Signal-to-Site Configuration
# Generated by setup.sh on $(date)

# ============================================================
# Required: LLM Provider
# ============================================================
${anthropic_key:+ANTHROPIC_API_KEY=$anthropic_key}

# ============================================================
# Required: Your Company Info
# ============================================================
YOUR_COMPANY_NAME="$company_name"
YOUR_VALUE_PROP="$value_prop"
SENDER_NAME="$sender_name"
SENDER_TITLE="$sender_title"
${sender_email:+SENDER_EMAIL=$sender_email}
CTA_URL="$cta_url"

# ============================================================
# Optional: Linkt Integration
# ============================================================
${linkt_key:+LINKT_API_KEY=$linkt_key}

# ============================================================
# Optional: Deployment
# ============================================================
DEPLOY_PLATFORM="${netlify_token:+netlify}"
${netlify_token:+NETLIFY_TOKEN=$netlify_token}

# ============================================================
# Optional: Notifications
# ============================================================
${slack_webhook:+SLACK_WEBHOOK_URL=$slack_webhook}
EOF

echo -e "${GREEN}✓ Created .env file${NC}"

# Create output directory
mkdir -p output
echo -e "${GREEN}✓ Created output directory${NC}"

echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Installing OpenClaw Plugin...${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo ""

# Install the plugin
if openclaw plugins install . 2>/dev/null; then
    echo -e "${GREEN}✓ Plugin installed${NC}"
else
    echo -e "${YELLOW}Note: Plugin install may require OpenClaw daemon running${NC}"
    echo "Try: openclaw plugins install ."
fi

echo ""
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Setup Complete!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo ""

echo -e "${GREEN}You're ready to demo Signal-to-Site!${NC}"
echo ""
echo "Quick start:"
echo ""
echo "  1. Start OpenClaw chat:"
echo -e "     ${YELLOW}openclaw chat${NC}"
echo ""
echo "  2. Run signal-to-site:"
echo -e "     ${YELLOW}/signal-to-site stripe.com hiring Head of Sales${NC}"
echo ""
echo "  3. Or use natural language:"
echo -e "     ${YELLOW}\"Research linear.app and create outreach for them\"${NC}"
echo ""

if [ -z "$netlify_token" ]; then
    echo -e "${YELLOW}Note: Pages will save locally to ./output/${NC}"
    echo "Add NETLIFY_TOKEN to .env for live URLs."
    echo ""
fi

if [ -z "$linkt_key" ]; then
    echo -e "${YELLOW}Note: Using demo signals (no Linkt key)${NC}"
    echo "Add LINKT_API_KEY to .env for real GTM signals."
    echo ""
fi

echo "For the full demo script, see: DEMO.md"
echo ""

# Offer to run a test
read -p "Run a quick test now? (Y/n): " run_test
if [[ ! $run_test =~ ^[Nn]$ ]]; then
    echo ""
    echo -e "${YELLOW}Testing with stripe.com...${NC}"
    echo ""

    # Source the .env
    set -a
    source .env
    set +a

    # Try to run a quick test
    if command -v python3 &> /dev/null; then
        python3 -c "
from signal_to_site.cli import main
import sys
sys.argv = ['signal-to-site', '--domain', 'stripe.com', '--demo', '--json']
" 2>/dev/null && echo -e "${GREEN}✓ Test passed!${NC}" || echo -e "${YELLOW}Run 'pip install -e .' first for Python CLI${NC}"
    fi

    echo ""
    echo "For the full browser-powered demo, run:"
    echo -e "  ${YELLOW}openclaw chat${NC}"
    echo -e "  ${YELLOW}/signal-to-site stripe.com hiring Head of Sales${NC}"
fi

echo ""
echo -e "${GREEN}Setup complete. Happy demoing! 🎯${NC}"
echo ""
