"""Page deployment module - deploys landing pages to hosting platforms."""

import os
import json
import base64
import httpx
from pathlib import Path
from typing import Optional
from datetime import datetime

from .models import GeneratedPage


class NetlifyDeployer:
    """Deploy pages to Netlify."""

    BASE_URL = "https://api.netlify.com/api/v1"

    def __init__(self, token: Optional[str] = None, site_id: Optional[str] = None):
        self.token = token or os.getenv("NETLIFY_TOKEN")
        self.site_id = site_id or os.getenv("NETLIFY_SITE_ID")

        if not self.token:
            raise ValueError("NETLIFY_TOKEN is required")

        self.client = httpx.Client(
            base_url=self.BASE_URL,
            headers={
                "Authorization": f"Bearer {self.token}",
                "Content-Type": "application/json",
            },
            timeout=60.0,
        )

    def deploy_page(self, page: GeneratedPage) -> str:
        """
        Deploy a single landing page.

        Returns the deployed URL.
        """
        # Create a simple site structure
        files = {
            f"/{page.slug}/index.html": page.html_content,
            "/index.html": self._create_index_page([page]),
        }

        # Deploy using Netlify's file digest API
        deploy_data = self._create_deploy(files)
        deployed_url = f"https://{deploy_data['subdomain']}.netlify.app/{page.slug}"

        return deployed_url

    def deploy_pages(self, pages: list[GeneratedPage], site_name: Optional[str] = None) -> dict:
        """
        Deploy multiple landing pages as a single site.

        Returns dict mapping slugs to URLs.
        """
        # Build file structure
        files = {"/index.html": self._create_index_page(pages)}

        for page in pages:
            files[f"/{page.slug}/index.html"] = page.html_content

        # Create or update site
        if not self.site_id:
            site = self._create_site(site_name or f"signal-to-site-{datetime.now().strftime('%Y%m%d')}")
            self.site_id = site["id"]

        deploy_data = self._create_deploy(files)
        base_url = f"https://{deploy_data['subdomain']}.netlify.app"

        return {page.slug: f"{base_url}/{page.slug}" for page in pages}

    def _create_site(self, name: str) -> dict:
        """Create a new Netlify site."""
        response = self.client.post("/sites", json={"name": name})
        response.raise_for_status()
        return response.json()

    def _create_deploy(self, files: dict[str, str]) -> dict:
        """Create a deploy with the given files."""
        # Calculate SHA1 hashes for each file
        import hashlib

        file_digests = {}
        file_contents = {}

        for path, content in files.items():
            content_bytes = content.encode("utf-8")
            sha1 = hashlib.sha1(content_bytes).hexdigest()
            file_digests[path] = sha1
            file_contents[sha1] = content_bytes

        # Create deploy
        response = self.client.post(
            f"/sites/{self.site_id}/deploys",
            json={"files": file_digests},
        )
        response.raise_for_status()
        deploy = response.json()

        # Upload required files
        for sha1 in deploy.get("required", []):
            if sha1 in file_contents:
                self.client.put(
                    f"/deploys/{deploy['id']}/files/{sha1}",
                    content=file_contents[sha1],
                    headers={"Content-Type": "application/octet-stream"},
                )

        return deploy

    def _create_index_page(self, pages: list[GeneratedPage]) -> str:
        """Create an index page listing all landing pages."""
        links = "\n".join(
            f'<li><a href="/{p.slug}/">{p.company.name}</a> - {p.company.signal_type}</li>'
            for p in pages
        )
        return f"""<!DOCTYPE html>
<html>
<head>
    <title>Signal-to-Site Pages</title>
    <style>
        body {{ font-family: system-ui; max-width: 600px; margin: 40px auto; padding: 20px; }}
        h1 {{ color: #2563eb; }}
        ul {{ list-style: none; padding: 0; }}
        li {{ padding: 12px 0; border-bottom: 1px solid #eee; }}
        a {{ color: #2563eb; text-decoration: none; font-weight: 500; }}
        a:hover {{ text-decoration: underline; }}
    </style>
</head>
<body>
    <h1>Generated Landing Pages</h1>
    <p>Pages generated by Signal-to-Site pipeline:</p>
    <ul>{links}</ul>
    <p><small>Generated: {datetime.now().isoformat()}</small></p>
</body>
</html>"""

    def close(self):
        self.client.close()


class LocalDeployer:
    """Save pages locally (for development/demo)."""

    def __init__(self, output_dir: str = "./output"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def deploy_page(self, page: GeneratedPage) -> str:
        """Save page locally and return file path."""
        page_dir = self.output_dir / page.slug
        page_dir.mkdir(exist_ok=True)

        page_file = page_dir / "index.html"
        page_file.write_text(page.html_content)

        return f"file://{page_file.absolute()}"

    def deploy_pages(self, pages: list[GeneratedPage]) -> dict:
        """Save multiple pages locally."""
        # Create index page
        index_content = self._create_index_page(pages)
        (self.output_dir / "index.html").write_text(index_content)

        urls = {}
        for page in pages:
            urls[page.slug] = self.deploy_page(page)

        return urls

    def _create_index_page(self, pages: list[GeneratedPage]) -> str:
        """Create index page for local viewing."""
        links = "\n".join(
            f'<li><a href="./{p.slug}/">{p.company.name}</a> - {p.company.signal_type}</li>'
            for p in pages
        )
        return f"""<!DOCTYPE html>
<html>
<head>
    <title>Signal-to-Site Pages</title>
    <style>
        body {{ font-family: system-ui; max-width: 600px; margin: 40px auto; padding: 20px; }}
        h1 {{ color: #2563eb; }}
        ul {{ list-style: none; padding: 0; }}
        li {{ padding: 12px 0; border-bottom: 1px solid #eee; }}
        a {{ color: #2563eb; text-decoration: none; font-weight: 500; }}
        a:hover {{ text-decoration: underline; }}
    </style>
</head>
<body>
    <h1>Generated Landing Pages</h1>
    <p>Pages generated by Signal-to-Site pipeline:</p>
    <ul>{links}</ul>
    <p><small>Generated: {datetime.now().isoformat()}</small></p>
</body>
</html>"""


def get_deployer(
    platform: str = "local",
    **kwargs,
) -> NetlifyDeployer | LocalDeployer:
    """
    Get appropriate deployer.

    Args:
        platform: "netlify" or "local"
    """
    if platform == "netlify":
        return NetlifyDeployer(**kwargs)
    return LocalDeployer(**kwargs)
