"""Notification module - sends alerts via Slack/Telegram."""

import os
import httpx
from typing import Optional

from .models import Company, GeneratedPage, OutreachDraft


class SlackNotifier:
    """Send notifications to Slack via webhook."""

    def __init__(self, webhook_url: Optional[str] = None):
        self.webhook_url = webhook_url or os.getenv("SLACK_WEBHOOK_URL")
        if not self.webhook_url:
            raise ValueError("SLACK_WEBHOOK_URL is required")

    def send_pipeline_result(
        self,
        company: Company,
        page: GeneratedPage,
        outreach: OutreachDraft,
    ) -> bool:
        """Send notification about completed pipeline run."""
        blocks = [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"New Signal: {company.name}",
                },
            },
            {
                "type": "section",
                "fields": [
                    {"type": "mrkdwn", "text": f"*Signal Type:*\n{company.signal_type}"},
                    {"type": "mrkdwn", "text": f"*Details:*\n{company.signal_details or 'N/A'}"},
                    {"type": "mrkdwn", "text": f"*Industry:*\n{company.industry or 'Unknown'}"},
                    {"type": "mrkdwn", "text": f"*Location:*\n{company.location or 'Unknown'}"},
                ],
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Landing Page:* <{page.deployed_url}|View Page>",
                },
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*Email Subject:*\n{outreach.email_subject}",
                },
            },
            {
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {"type": "plain_text", "text": "View Landing Page"},
                        "url": page.deployed_url or "#",
                    },
                ],
            },
        ]

        return self._send({"blocks": blocks})

    def send_message(self, text: str) -> bool:
        """Send a simple text message."""
        return self._send({"text": text})

    def _send(self, payload: dict) -> bool:
        """Send payload to Slack webhook."""
        try:
            response = httpx.post(self.webhook_url, json=payload, timeout=10.0)
            return response.status_code == 200
        except Exception as e:
            print(f"Failed to send Slack notification: {e}")
            return False


class TelegramNotifier:
    """Send notifications via Telegram bot."""

    BASE_URL = "https://api.telegram.org"

    def __init__(
        self,
        bot_token: Optional[str] = None,
        chat_id: Optional[str] = None,
    ):
        self.bot_token = bot_token or os.getenv("TELEGRAM_BOT_TOKEN")
        self.chat_id = chat_id or os.getenv("TELEGRAM_CHAT_ID")

        if not self.bot_token or not self.chat_id:
            raise ValueError("TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID are required")

    def send_pipeline_result(
        self,
        company: Company,
        page: GeneratedPage,
        outreach: OutreachDraft,
    ) -> bool:
        """Send notification about completed pipeline run."""
        message = f"""
*New Signal Detected*

*Company:* {company.name}
*Signal:* {company.signal_type} - {company.signal_details or 'N/A'}
*Industry:* {company.industry or 'Unknown'}
*Location:* {company.location or 'Unknown'}

*Landing Page:* [View]({page.deployed_url})

*Email Subject:* {outreach.email_subject}

---
_Generated by Signal-to-Site_
"""
        return self.send_message(message, parse_mode="Markdown")

    def send_message(self, text: str, parse_mode: str = "Markdown") -> bool:
        """Send a message via Telegram."""
        try:
            url = f"{self.BASE_URL}/bot{self.bot_token}/sendMessage"
            response = httpx.post(
                url,
                json={
                    "chat_id": self.chat_id,
                    "text": text,
                    "parse_mode": parse_mode,
                },
                timeout=10.0,
            )
            return response.status_code == 200
        except Exception as e:
            print(f"Failed to send Telegram notification: {e}")
            return False


class MockNotifier:
    """Mock notifier for demo (just prints)."""

    def send_pipeline_result(
        self,
        company: Company,
        page: GeneratedPage,
        outreach: OutreachDraft,
    ) -> bool:
        print(f"\n[NOTIFICATION] Pipeline complete for {company.name}")
        print(f"  Signal: {company.signal_type} - {company.signal_details}")
        print(f"  Page: {page.deployed_url or page.slug}")
        print(f"  Email: {outreach.email_subject}\n")
        return True

    def send_message(self, text: str) -> bool:
        print(f"\n[NOTIFICATION] {text}\n")
        return True


class NullNotifier:
    """Null notifier that does nothing (for quiet/JSON mode)."""

    def send_pipeline_result(self, *args, **kwargs) -> bool:
        return True

    def send_message(self, *args, **kwargs) -> bool:
        return True


def get_notifier(
    platform: str = "mock",
    **kwargs,
) -> SlackNotifier | TelegramNotifier | MockNotifier | NullNotifier:
    """
    Get appropriate notifier.

    Args:
        platform: "slack", "telegram", "mock", or "none"
    """
    if platform == "slack":
        return SlackNotifier(**kwargs)
    elif platform == "telegram":
        return TelegramNotifier(**kwargs)
    elif platform == "none":
        return NullNotifier()
    return MockNotifier()
